### ISSUE TITLE
tests files should start with the word test

### ISSUE THREAD

**Issue by codedragon** [UWPCE-PythonCert/PythonCertDevel220#15]
Hi there,
Great job updating the materials! I'm a set of fresh eyes, so I'm going to see stuff you haven't seen. Don't hold it against me. ;-) 

In the assignment for lesson 1: modules/lesson01/assignment.html
you ask the students to create a file unit_tests.py for putting tests in. 
Can we call this test_unit.py or test_unit_style.py instead? They should get in the habit of starting the names of all test files with the word test so that test runners can find them. So, also make integration_test.py test_integration.py or something like that.

**Comment by pythonsavvy** [comment]
fixed names of tests in l1
